### ISSUE TITLE
A for Effort but...

### ISSUE THREAD

**Issue by TKFRvisionOfficial** [okok7711/lernsax#5]
Well,

I forked this because I just wanted to add some functionality, but..., well...There are some issues.
- Formating is a catastrophe.
- APIClient wouldn't work on it own making abstract. But the class isn't marked abstract.
- Please define variables that you are using in fuctions of a class
- there are lots of function which shouldn't be async but are anyways. (for example: pack_responses, jsonrpc). as a rule of thumb: "if there isn't a await statement it probaly isn't async"
- when you renamed functions you accidently also changed values in strings (for example: "await self.jsonrpc")
- Why do you use BeautifulSoup to get the tasks? You can set the focus to "tasks" and then "get_entries".
- You are using the session_id everywhere I look. If you wait to long (like 20min) and will expire. I would first of all use the "get_information" command after every request to get a new session_id. I would also implement the token system.

You linked to my repo in your README.md. I am actually sorry for never writing a proper documentation.  It is actually harder then I thought it would be and I would need help for that. I have a lot of code implementing this api which I haven't published but probaly should have. If you still want to go forward with this project I would like to help you. So hit me up. I also know another person who knows his stuff around here.

**Comment by okok7711** [comment]
Hey! The formatting was done automatically, I agree that it isn't the best.

The session_id was my least concern you could add a background task to refresh the session id all the time

As for the tasks part, I didn't know that was possible I only looked at the app's functionality and captured the requests, since there's no functionality for it in the app, I also couldn't find the possibility of it

I'll rewrite this soon enough to implement the fixes

**Comment by TKFRvisionOfficial** [comment]
your code looks way better now. although i still don't understand why you need this abstract class you marked it as such making this way better... congrats...

if you want to you can credit me 😂... if you don't thats fine too...

**Comment by TKFRvisionOfficial** [comment]
you code looks way better now...congrats...

as for the deleted comment: i confused you for a different person sry mate...
